version: '2'

services:
  python_parser:
    extends:
      file: common.yml
      service: python_parser
    ports:
      - "25252:25252"
  python2_parser:
    extends:
      file: common.yml
      service: python2_parser
    ports:
      - "25253:25253"
